// @generated by protoc-gen-knit-ts v0.0.7 with parameter "target=dts"
// @generated from file spec/all.proto (package spec, syntax proto3)
/* eslint-disable */

import type { Wkt } from "./wkt_knit";
import type { Scalar } from "./scalars_knit";
import type { Map } from "./map_knit";
import type { Oneof } from "./oneof_knit";
import type { Message } from "./messages_knit";
import type { EnumShell, TopLevel } from "./enum_knit";
export type AllService = {
    "spec.AllService": {
        fetch: {
            getAll: {
                $: All;
                value: All;
            };
        };
        do: {
            createAll: {
                $: All;
                value: All;
            };
        };
        listen: {
            streamAll: {
                $: All;
                value: All;
            };
        };
    };
};
export interface All {
    self?: All;
    wkt?: Wkt;
    scalars?: Scalar;
    map?: Map;
    oneof?: Oneof;
    message?: Message;
    enum: {
        "@enum": TopLevel;
    };
    enumShell?: EnumShell;
}
