// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/all.proto (package spec, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Wkt } from "./wkt_pb.js";
import type { Scalar } from "./scalars_pb.js";
import type { Map } from "./map_pb.js";
import type { Oneof } from "./oneof_pb.js";
import type { Message as Message$1 } from "./messages_pb.js";
import type { EnumShell, TopLevel } from "./enum_pb.js";

/**
 * Describes the file spec/all.proto.
 */
export declare const file_spec_all: GenFile;

/**
 * @generated from message spec.All
 */
export declare type All = Message<"spec.All"> & {
  /**
   * @generated from field: spec.All self = 1;
   */
  self?: All | undefined;

  /**
   * @generated from field: spec.Wkt wkt = 2;
   */
  wkt?: Wkt | undefined;

  /**
   * @generated from field: spec.Scalar scalars = 3;
   */
  scalars?: Scalar | undefined;

  /**
   * @generated from field: spec.Map map = 4;
   */
  map?: Map | undefined;

  /**
   * @generated from field: spec.Oneof oneof = 5;
   */
  oneof?: Oneof | undefined;

  /**
   * @generated from field: spec.Message message = 6;
   */
  message?: Message$1 | undefined;

  /**
   * @generated from field: spec.TopLevel enum = 7;
   */
  enum: TopLevel;

  /**
   * @generated from field: spec.EnumShell enum_shell = 8;
   */
  enumShell?: EnumShell | undefined;
};

/**
 * Describes the message spec.All.
 * Use `create(AllSchema)` to create a new message.
 */
export declare const AllSchema: GenMessage<All>;

/**
 * @generated from service spec.AllService
 */
export declare const AllService: GenService<{
  /**
   * @generated from rpc spec.AllService.GetAll
   */
  getAll: {
    methodKind: "unary";
    input: typeof AllSchema;
    output: typeof AllSchema;
  },
  /**
   * @generated from rpc spec.AllService.CreateAll
   */
  createAll: {
    methodKind: "unary";
    input: typeof AllSchema;
    output: typeof AllSchema;
  },
  /**
   * @generated from rpc spec.AllService.StreamAll
   */
  streamAll: {
    methodKind: "server_streaming";
    input: typeof AllSchema;
    output: typeof AllSchema;
  },
  /**
   * @generated from rpc spec.AllService.ClientAll
   */
  clientAll: {
    methodKind: "client_streaming";
    input: typeof AllSchema;
    output: typeof AllSchema;
  },
  /**
   * @generated from rpc spec.AllService.BiDiAll
   */
  biDiAll: {
    methodKind: "bidi_streaming";
    input: typeof AllSchema;
    output: typeof AllSchema;
  },
}>;

