// @generated by protoc-gen-connect-es v1.0.0
// @generated from file spec/all.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { All } from "./all_pb.js";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service spec.AllService
 */
export declare const AllService: {
  readonly typeName: "spec.AllService",
  readonly methods: {
    /**
     * @generated from rpc spec.AllService.GetAll
     */
    readonly getAll: {
      readonly name: "GetAll",
      readonly I: typeof All,
      readonly O: typeof All,
      readonly kind: MethodKind.Unary,
      readonly idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc spec.AllService.CreateAll
     */
    readonly createAll: {
      readonly name: "CreateAll",
      readonly I: typeof All,
      readonly O: typeof All,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.AllService.StreamAll
     */
    readonly streamAll: {
      readonly name: "StreamAll",
      readonly I: typeof All,
      readonly O: typeof All,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc spec.AllService.ClientAll
     */
    readonly clientAll: {
      readonly name: "ClientAll",
      readonly I: typeof All,
      readonly O: typeof All,
      readonly kind: MethodKind.ClientStreaming,
    },
    /**
     * @generated from rpc spec.AllService.BiDiAll
     */
    readonly biDiAll: {
      readonly name: "BiDiAll",
      readonly I: typeof All,
      readonly O: typeof All,
      readonly kind: MethodKind.BiDiStreaming,
    },
  }
};

