// @generated by protoc-gen-es v1.5.0
// @generated from file spec/all.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Wkt } from "./wkt_pb.js";
import { Scalar } from "./scalars_pb.js";
import { Map } from "./map_pb.js";
import { Oneof } from "./oneof_pb.js";
import { Message } from "./messages_pb.js";
import { EnumShell, TopLevel } from "./enum_pb.js";

/**
 * @generated from message spec.All
 */
export const All = proto3.makeMessageType(
  "spec.All",
  () => [
    { no: 1, name: "self", kind: "message", T: All },
    { no: 2, name: "wkt", kind: "message", T: Wkt },
    { no: 3, name: "scalars", kind: "message", T: Scalar },
    { no: 4, name: "map", kind: "message", T: Map },
    { no: 5, name: "oneof", kind: "message", T: Oneof },
    { no: 6, name: "message", kind: "message", T: Message },
    { no: 7, name: "enum", kind: "enum", T: proto3.getEnumType(TopLevel) },
    { no: 8, name: "enum_shell", kind: "message", T: EnumShell },
  ],
);

