// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/all.proto (package spec, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_spec_enum } from "./enum_pb.js";
import { file_spec_map } from "./map_pb.js";
import { file_spec_messages } from "./messages_pb.js";
import { file_spec_oneof } from "./oneof_pb.js";
import { file_spec_scalars } from "./scalars_pb.js";
import { file_spec_wkt } from "./wkt_pb.js";

/**
 * Describes the file spec/all.proto.
 */
export const file_spec_all = /*@__PURE__*/
  fileDesc("Cg5zcGVjL2FsbC5wcm90bxIEc3BlYyLsAQoDQWxsEhcKBHNlbGYYASABKAsyCS5zcGVjLkFsbBIWCgN3a3QYAiABKAsyCS5zcGVjLldrdBIdCgdzY2FsYXJzGAMgASgLMgwuc3BlYy5TY2FsYXISFgoDbWFwGAQgASgLMgkuc3BlYy5NYXASGgoFb25lb2YYBSABKAsyCy5zcGVjLk9uZW9mEh4KB21lc3NhZ2UYBiABKAsyDS5zcGVjLk1lc3NhZ2USHAoEZW51bRgHIAEoDjIOLnNwZWMuVG9wTGV2ZWwSIwoKZW51bV9zaGVsbBgIIAEoCzIPLnNwZWMuRW51bVNoZWxsMsMBCgpBbGxTZXJ2aWNlEiMKBkdldEFsbBIJLnNwZWMuQWxsGgkuc3BlYy5BbGwiA5ACARIhCglDcmVhdGVBbGwSCS5zcGVjLkFsbBoJLnNwZWMuQWxsEiMKCVN0cmVhbUFsbBIJLnNwZWMuQWxsGgkuc3BlYy5BbGwwARIjCglDbGllbnRBbGwSCS5zcGVjLkFsbBoJLnNwZWMuQWxsKAESIwoHQmlEaUFsbBIJLnNwZWMuQWxsGgkuc3BlYy5BbGwoATABYgZwcm90bzM", [file_spec_enum, file_spec_map, file_spec_messages, file_spec_oneof, file_spec_scalars, file_spec_wkt]);

/**
 * Describes the message spec.All.
 * Use `create(AllSchema)` to create a new message.
 */
export const AllSchema = /*@__PURE__*/
  messageDesc(file_spec_all, 0);

/**
 * @generated from service spec.AllService
 */
export const AllService = /*@__PURE__*/
  serviceDesc(file_spec_all, 0);

