// @generated by protoc-gen-knit-ts v0.0.2
// @generated from file spec/all.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { Wkt } from "./wkt_knit.js";
import type { Scalar } from "./scalars_knit.js";
import type { Map } from "./map_knit.js";
import type { Oneof } from "./oneof_knit.js";
import type { Message } from "./messages_knit.js";
import type { EnumShell, TopLevel } from "./enum_knit.js";
export declare type AllService = {
    "spec.AllService": {
        fetch: {
            getAll: {
                $: All;
                value: All;
            };
        };
        do: {
            createAll: {
                $: All;
                value: All;
            };
        };
        listen: {
            streamAll: {
                $: All;
                value: All;
            };
        };
    };
};
export interface All {
    self?: All;
    wkt?: Wkt;
    scalars?: Scalar;
    map?: Map;
    oneof?: Oneof;
    message?: Message;
    enum: {
        "@enum": TopLevel;
    };
    enumShell?: EnumShell;
}
