// @generated by protoc-gen-connect-es v1.1.3
// @generated from file spec/all.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { All } from "./all_pb.js";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service spec.AllService
 */
export const AllService = {
  typeName: "spec.AllService",
  methods: {
    /**
     * @generated from rpc spec.AllService.GetAll
     */
    getAll: {
      name: "GetAll",
      I: All,
      O: All,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc spec.AllService.CreateAll
     */
    createAll: {
      name: "CreateAll",
      I: All,
      O: All,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.AllService.StreamAll
     */
    streamAll: {
      name: "StreamAll",
      I: All,
      O: All,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc spec.AllService.ClientAll
     */
    clientAll: {
      name: "ClientAll",
      I: All,
      O: All,
      kind: MethodKind.ClientStreaming,
    },
    /**
     * @generated from rpc spec.AllService.BiDiAll
     */
    biDiAll: {
      name: "BiDiAll",
      I: All,
      O: All,
      kind: MethodKind.BiDiStreaming,
    },
  }
};

