// @generated by protoc-gen-knit-ts v0.0.3
// @generated from file spec/enum.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

export interface EnumShell {
    optionalEnum?: {
        "@enum": EnumShell_InsideMessage;
    };
}
export declare type EnumShell_InsideMessage = "THIRD" | "FOURTH" | number;
export declare type TopLevel = "FIRST" | "SECOND" | number;
