// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/enum.proto (package spec, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spec/enum.proto.
 */
export declare const file_spec_enum: GenFile;

/**
 * @generated from message spec.EnumShell
 */
export declare type EnumShell = Message<"spec.EnumShell"> & {
  /**
   * @generated from field: optional spec.EnumShell.InsideMessage optional_enum = 1;
   */
  optionalEnum?: EnumShell_InsideMessage | undefined;
};

/**
 * Describes the message spec.EnumShell.
 * Use `create(EnumShellSchema)` to create a new message.
 */
export declare const EnumShellSchema: GenMessage<EnumShell>;

/**
 * @generated from enum spec.EnumShell.InsideMessage
 */
export enum EnumShell_InsideMessage {
  /**
   * @generated from enum value: THIRD = 0;
   */
  THIRD = 0,

  /**
   * @generated from enum value: FOURTH = 1;
   */
  FOURTH = 1,
}

/**
 * Describes the enum spec.EnumShell.InsideMessage.
 */
export declare const EnumShell_InsideMessageSchema: GenEnum<EnumShell_InsideMessage>;

/**
 * @generated from enum spec.TopLevel
 */
export enum TopLevel {
  /**
   * @generated from enum value: FIRST = 0;
   */
  FIRST = 0,

  /**
   * @generated from enum value: SECOND = 1;
   */
  SECOND = 1,
}

/**
 * Describes the enum spec.TopLevel.
 */
export declare const TopLevelSchema: GenEnum<TopLevel>;

