// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/enum.proto (package spec, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file spec/enum.proto.
 */
export const file_spec_enum = /*@__PURE__*/
  fileDesc("Cg9zcGVjL2VudW0ucHJvdG8SBHNwZWMigAEKCUVudW1TaGVsbBI5Cg1vcHRpb25hbF9lbnVtGAEgASgOMh0uc3BlYy5FbnVtU2hlbGwuSW5zaWRlTWVzc2FnZUgAiAEBIiYKDUluc2lkZU1lc3NhZ2USCQoFVEhJUkQQABIKCgZGT1VSVEgQAUIQCg5fb3B0aW9uYWxfZW51bSohCghUb3BMZXZlbBIJCgVGSVJTVBAAEgoKBlNFQ09ORBABYgZwcm90bzM");

/**
 * Describes the message spec.EnumShell.
 * Use `create(EnumShellSchema)` to create a new message.
 */
export const EnumShellSchema = /*@__PURE__*/
  messageDesc(file_spec_enum, 0);

/**
 * Describes the enum spec.EnumShell.InsideMessage.
 */
export const EnumShell_InsideMessageSchema = /*@__PURE__*/
  enumDesc(file_spec_enum, 0, 0);

/**
 * @generated from enum spec.EnumShell.InsideMessage
 */
export const EnumShell_InsideMessage = /*@__PURE__*/
  tsEnum(EnumShell_InsideMessageSchema);

/**
 * Describes the enum spec.TopLevel.
 */
export const TopLevelSchema = /*@__PURE__*/
  enumDesc(file_spec_enum, 0);

/**
 * @generated from enum spec.TopLevel
 */
export const TopLevel = /*@__PURE__*/
  tsEnum(TopLevelSchema);

