// @generated by protoc-gen-knit-ts v0.0.7 with parameter "target=dts"
// @generated from file spec/enum.proto (package spec, syntax proto3)
/* eslint-disable */

export interface EnumShell {
    optionalEnum?: {
        "@enum": EnumShell_InsideMessage;
    };
}
export type EnumShell_InsideMessage = "THIRD" | "FOURTH" | number;
export type TopLevel = "FIRST" | "SECOND" | number;
