// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/json.proto (package spec, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file spec/json.proto.
 */
export const file_spec_json = /*@__PURE__*/
  fileDesc("Cg9zcGVjL2pzb24ucHJvdG8SBHNwZWMiKAoOQ3VzdG9tSnNvbk5hbWUSFgoEbmFtZRgBIAEoCVIIbm90X25hbWViBnByb3RvMw");

/**
 * Describes the message spec.CustomJsonName.
 * Use `create(CustomJsonNameSchema)` to create a new message.
 */
export const CustomJsonNameSchema = /*@__PURE__*/
  messageDesc(file_spec_json, 0);

