// @generated by protoc-gen-es v1.2.0
// @generated from file spec/json.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message spec.CustomJsonName
 */
export declare class CustomJsonName extends Message<CustomJsonName> {
  /**
   * @generated from field: string name = 1 [json_name = "not_name"];
   */
  name: string;

  constructor(data?: PartialMessage<CustomJsonName>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "spec.CustomJsonName";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CustomJsonName;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CustomJsonName;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CustomJsonName;

  static equals(a: CustomJsonName | PlainMessage<CustomJsonName> | undefined, b: CustomJsonName | PlainMessage<CustomJsonName> | undefined): boolean;
}

