// @generated by protoc-gen-knit-ts v0.0.2
// @generated from file spec/json.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

export interface CustomJsonName {
    name: {
        "@alias": "not_name";
        value: string;
    };
}
