// @generated by protoc-gen-knit-ts v0.0.7 with parameter "target=dts"
// @generated from file spec/json.proto (package spec, syntax proto3)
/* eslint-disable */

export interface CustomJsonName {
    name: {
        "@alias": "not_name";
        value: string;
    };
}
