// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/json.proto (package spec, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spec/json.proto.
 */
export declare const file_spec_json: GenFile;

/**
 * @generated from message spec.CustomJsonName
 */
export declare type CustomJsonName = Message<"spec.CustomJsonName"> & {
  /**
   * @generated from field: string name = 1 [json_name = "not_name"];
   */
  name: string;
};

/**
 * Describes the message spec.CustomJsonName.
 * Use `create(CustomJsonNameSchema)` to create a new message.
 */
export declare const CustomJsonNameSchema: GenMessage<CustomJsonName>;

