// @generated by protoc-gen-knit-ts v0.0.5
// @generated from file spec/map.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

export interface Map {
    keys?: Keys;
    message: {
        "@map": {
            [k: string]: Map;
        };
    };
    enum: {
        "@map": {
            [k: string]: {
                "@enum": MapEnum;
            };
        };
    };
}
export interface Keys {
    str: {
        "@map": {
            [k: string]: string;
        };
    };
    bl: {
        "@map": {
            [k: string]: string;
        };
    };
    i32: {
        "@map": {
            [k: number]: string;
        };
    };
    i64: {
        "@map": {
            [k: string]: string;
        };
    };
    u32: {
        "@map": {
            [k: number]: string;
        };
    };
    u64: {
        "@map": {
            [k: string]: string;
        };
    };
    s32: {
        "@map": {
            [k: number]: string;
        };
    };
    s64: {
        "@map": {
            [k: string]: string;
        };
    };
    f32: {
        "@map": {
            [k: number]: string;
        };
    };
    f64: {
        "@map": {
            [k: string]: string;
        };
    };
    sf32: {
        "@map": {
            [k: number]: string;
        };
    };
    sf64: {
        "@map": {
            [k: string]: string;
        };
    };
}
export declare type MapEnum = "MAP_ENUM_UNSPECIFIED" | "MAP_ENUM_FIRST" | number;
