// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/map.proto (package spec, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spec/map.proto.
 */
export declare const file_spec_map: GenFile;

/**
 * @generated from message spec.Map
 */
export declare type Map = Message<"spec.Map"> & {
  /**
   * @generated from field: spec.Keys keys = 1;
   */
  keys?: Keys | undefined;

  /**
   * @generated from field: map<string, spec.Map> message = 2;
   */
  message: { [key: string]: Map };

  /**
   * @generated from field: map<string, spec.MapEnum> enum = 3;
   */
  enum: { [key: string]: MapEnum };
};

/**
 * Describes the message spec.Map.
 * Use `create(MapSchema)` to create a new message.
 */
export declare const MapSchema: GenMessage<Map>;

/**
 * @generated from message spec.Keys
 */
export declare type Keys = Message<"spec.Keys"> & {
  /**
   * @generated from field: map<string, string> str = 1;
   */
  str: { [key: string]: string };

  /**
   * @generated from field: map<bool, string> bl = 2;
   */
  bl: { [key: string]: string };

  /**
   * @generated from field: map<int32, string> i32 = 3;
   */
  i32: { [key: number]: string };

  /**
   * @generated from field: map<int64, string> i64 = 4;
   */
  i64: { [key: string]: string };

  /**
   * @generated from field: map<uint32, string> u32 = 5;
   */
  u32: { [key: number]: string };

  /**
   * @generated from field: map<uint64, string> u64 = 6;
   */
  u64: { [key: string]: string };

  /**
   * @generated from field: map<sint32, string> s32 = 7;
   */
  s32: { [key: number]: string };

  /**
   * @generated from field: map<sint64, string> s64 = 8;
   */
  s64: { [key: string]: string };

  /**
   * @generated from field: map<fixed32, string> f32 = 9;
   */
  f32: { [key: number]: string };

  /**
   * @generated from field: map<fixed64, string> f64 = 10;
   */
  f64: { [key: string]: string };

  /**
   * @generated from field: map<sfixed32, string> sf32 = 11;
   */
  sf32: { [key: number]: string };

  /**
   * @generated from field: map<sfixed64, string> sf64 = 12;
   */
  sf64: { [key: string]: string };
};

/**
 * Describes the message spec.Keys.
 * Use `create(KeysSchema)` to create a new message.
 */
export declare const KeysSchema: GenMessage<Keys>;

/**
 * @generated from enum spec.MapEnum
 */
export enum MapEnum {
  /**
   * @generated from enum value: MAP_ENUM_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MAP_ENUM_FIRST = 1;
   */
  FIRST = 1,
}

/**
 * Describes the enum spec.MapEnum.
 */
export declare const MapEnumSchema: GenEnum<MapEnum>;

