// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/map.proto (package spec, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file spec/map.proto.
 */
export const file_spec_map = /*@__PURE__*/
  fileDesc("Cg5zcGVjL21hcC5wcm90bxIEc3BlYyLiAQoDTWFwEhgKBGtleXMYASABKAsyCi5zcGVjLktleXMSJwoHbWVzc2FnZRgCIAMoCzIWLnNwZWMuTWFwLk1lc3NhZ2VFbnRyeRIhCgRlbnVtGAMgAygLMhMuc3BlYy5NYXAuRW51bUVudHJ5GjkKDE1lc3NhZ2VFbnRyeRILCgNrZXkYASABKAkSGAoFdmFsdWUYAiABKAsyCS5zcGVjLk1hcDoCOAEaOgoJRW51bUVudHJ5EgsKA2tleRgBIAEoCRIcCgV2YWx1ZRgCIAEoDjINLnNwZWMuTWFwRW51bToCOAEisQcKBEtleXMSIAoDc3RyGAEgAygLMhMuc3BlYy5LZXlzLlN0ckVudHJ5Eh4KAmJsGAIgAygLMhIuc3BlYy5LZXlzLkJsRW50cnkSIAoDaTMyGAMgAygLMhMuc3BlYy5LZXlzLkkzMkVudHJ5EiAKA2k2NBgEIAMoCzITLnNwZWMuS2V5cy5JNjRFbnRyeRIgCgN1MzIYBSADKAsyEy5zcGVjLktleXMuVTMyRW50cnkSIAoDdTY0GAYgAygLMhMuc3BlYy5LZXlzLlU2NEVudHJ5EiAKA3MzMhgHIAMoCzITLnNwZWMuS2V5cy5TMzJFbnRyeRIgCgNzNjQYCCADKAsyEy5zcGVjLktleXMuUzY0RW50cnkSIAoDZjMyGAkgAygLMhMuc3BlYy5LZXlzLkYzMkVudHJ5EiAKA2Y2NBgKIAMoCzITLnNwZWMuS2V5cy5GNjRFbnRyeRIiCgRzZjMyGAsgAygLMhQuc3BlYy5LZXlzLlNmMzJFbnRyeRIiCgRzZjY0GAwgAygLMhQuc3BlYy5LZXlzLlNmNjRFbnRyeRoqCghTdHJFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBGikKB0JsRW50cnkSCwoDa2V5GAEgASgIEg0KBXZhbHVlGAIgASgJOgI4ARoqCghJMzJFbnRyeRILCgNrZXkYASABKAUSDQoFdmFsdWUYAiABKAk6AjgBGioKCEk2NEVudHJ5EgsKA2tleRgBIAEoAxINCgV2YWx1ZRgCIAEoCToCOAEaKgoIVTMyRW50cnkSCwoDa2V5GAEgASgNEg0KBXZhbHVlGAIgASgJOgI4ARoqCghVNjRFbnRyeRILCgNrZXkYASABKAQSDQoFdmFsdWUYAiABKAk6AjgBGioKCFMzMkVudHJ5EgsKA2tleRgBIAEoERINCgV2YWx1ZRgCIAEoCToCOAEaKgoIUzY0RW50cnkSCwoDa2V5GAEgASgSEg0KBXZhbHVlGAIgASgJOgI4ARoqCghGMzJFbnRyeRILCgNrZXkYASABKAcSDQoFdmFsdWUYAiABKAk6AjgBGioKCEY2NEVudHJ5EgsKA2tleRgBIAEoBhINCgV2YWx1ZRgCIAEoCToCOAEaKwoJU2YzMkVudHJ5EgsKA2tleRgBIAEoDxINCgV2YWx1ZRgCIAEoCToCOAEaKwoJU2Y2NEVudHJ5EgsKA2tleRgBIAEoEBINCgV2YWx1ZRgCIAEoCToCOAEqNwoHTWFwRW51bRIYChRNQVBfRU5VTV9VTlNQRUNJRklFRBAAEhIKDk1BUF9FTlVNX0ZJUlNUEAFiBnByb3RvMw");

/**
 * Describes the message spec.Map.
 * Use `create(MapSchema)` to create a new message.
 */
export const MapSchema = /*@__PURE__*/
  messageDesc(file_spec_map, 0);

/**
 * Describes the message spec.Keys.
 * Use `create(KeysSchema)` to create a new message.
 */
export const KeysSchema = /*@__PURE__*/
  messageDesc(file_spec_map, 1);

/**
 * Describes the enum spec.MapEnum.
 */
export const MapEnumSchema = /*@__PURE__*/
  enumDesc(file_spec_map, 0);

/**
 * @generated from enum spec.MapEnum
 */
export const MapEnum = /*@__PURE__*/
  tsEnum(MapEnumSchema);

