// @generated by protoc-gen-es v1.3.0
// @generated from file spec/map.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum spec.MapEnum
 */
export const MapEnum = proto3.makeEnum(
  "spec.MapEnum",
  [
    {no: 0, name: "MAP_ENUM_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "MAP_ENUM_FIRST", localName: "FIRST"},
  ],
);

/**
 * @generated from message spec.Map
 */
export const Map = proto3.makeMessageType(
  "spec.Map",
  () => [
    { no: 1, name: "keys", kind: "message", T: Keys },
    { no: 2, name: "message", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Map} },
    { no: 3, name: "enum", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "enum", T: proto3.getEnumType(MapEnum)} },
  ],
);

/**
 * @generated from message spec.Keys
 */
export const Keys = proto3.makeMessageType(
  "spec.Keys",
  () => [
    { no: 1, name: "str", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 2, name: "bl", kind: "map", K: 8 /* ScalarType.BOOL */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 3, name: "i32", kind: "map", K: 5 /* ScalarType.INT32 */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 4, name: "i64", kind: "map", K: 3 /* ScalarType.INT64 */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 5, name: "u32", kind: "map", K: 13 /* ScalarType.UINT32 */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 6, name: "u64", kind: "map", K: 4 /* ScalarType.UINT64 */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 7, name: "s32", kind: "map", K: 17 /* ScalarType.SINT32 */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 8, name: "s64", kind: "map", K: 18 /* ScalarType.SINT64 */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 9, name: "f32", kind: "map", K: 7 /* ScalarType.FIXED32 */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 10, name: "f64", kind: "map", K: 6 /* ScalarType.FIXED64 */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 11, name: "sf32", kind: "map", K: 15 /* ScalarType.SFIXED32 */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 12, name: "sf64", kind: "map", K: 16 /* ScalarType.SFIXED64 */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ],
);

