// @generated by protoc-gen-es v1.5.0
// @generated from file spec/messages.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message as Message$1, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message spec.Message
 */
export declare class Message extends Message$1<Message> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: spec.Message.Inner inner = 2;
   */
  inner?: Message_Inner;

  /**
   * @generated from field: spec.Message.Inner.WithinInner within_inner = 3;
   */
  withinInner?: Message_Inner_WithinInner;

  /**
   * @generated from field: spec.Message self = 4;
   */
  self?: Message;

  /**
   * @generated from field: repeated spec.Message selfs = 5;
   */
  selfs: Message[];

  /**
   * @generated from field: map<string, spec.Message> self_map = 6;
   */
  selfMap: { [key: string]: Message };

  constructor(data?: PartialMessage<Message>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "spec.Message";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Message;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Message;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Message;

  static equals(a: Message | PlainMessage<Message> | undefined, b: Message | PlainMessage<Message> | undefined): boolean;
}

/**
 * @generated from message spec.Message.Inner
 */
export declare class Message_Inner extends Message$1<Message_Inner> {
  /**
   * @generated from field: optional spec.Message mess = 1;
   */
  mess?: Message;

  constructor(data?: PartialMessage<Message_Inner>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "spec.Message.Inner";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Message_Inner;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Message_Inner;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Message_Inner;

  static equals(a: Message_Inner | PlainMessage<Message_Inner> | undefined, b: Message_Inner | PlainMessage<Message_Inner> | undefined): boolean;
}

/**
 * @generated from message spec.Message.Inner.WithinInner
 */
export declare class Message_Inner_WithinInner extends Message$1<Message_Inner_WithinInner> {
  /**
   * @generated from field: float fl = 1;
   */
  fl: number;

  constructor(data?: PartialMessage<Message_Inner_WithinInner>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "spec.Message.Inner.WithinInner";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Message_Inner_WithinInner;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Message_Inner_WithinInner;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Message_Inner_WithinInner;

  static equals(a: Message_Inner_WithinInner | PlainMessage<Message_Inner_WithinInner> | undefined, b: Message_Inner_WithinInner | PlainMessage<Message_Inner_WithinInner> | undefined): boolean;
}

