// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/messages.proto (package spec, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file spec/messages.proto.
 */
export const file_spec_messages = /*@__PURE__*/
  fileDesc("ChNzcGVjL21lc3NhZ2VzLnByb3RvEgRzcGVjIucCCgdNZXNzYWdlEgoKAmlkGAEgASgJEiIKBWlubmVyGAIgASgLMhMuc3BlYy5NZXNzYWdlLklubmVyEjUKDHdpdGhpbl9pbm5lchgDIAEoCzIfLnNwZWMuTWVzc2FnZS5Jbm5lci5XaXRoaW5Jbm5lchIbCgRzZWxmGAQgASgLMg0uc3BlYy5NZXNzYWdlEhwKBXNlbGZzGAUgAygLMg0uc3BlYy5NZXNzYWdlEiwKCHNlbGZfbWFwGAYgAygLMhouc3BlYy5NZXNzYWdlLlNlbGZNYXBFbnRyeRpNCgVJbm5lchIgCgRtZXNzGAEgASgLMg0uc3BlYy5NZXNzYWdlSACIAQEaGQoLV2l0aGluSW5uZXISCgoCZmwYASABKAJCBwoFX21lc3MaPQoMU2VsZk1hcEVudHJ5EgsKA2tleRgBIAEoCRIcCgV2YWx1ZRgCIAEoCzINLnNwZWMuTWVzc2FnZToCOAFiBnByb3RvMw");

/**
 * Describes the message spec.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema = /*@__PURE__*/
  messageDesc(file_spec_messages, 0);

/**
 * Describes the message spec.Message.Inner.
 * Use `create(Message_InnerSchema)` to create a new message.
 */
export const Message_InnerSchema = /*@__PURE__*/
  messageDesc(file_spec_messages, 0, 0);

/**
 * Describes the message spec.Message.Inner.WithinInner.
 * Use `create(Message_Inner_WithinInnerSchema)` to create a new message.
 */
export const Message_Inner_WithinInnerSchema = /*@__PURE__*/
  messageDesc(file_spec_messages, 0, 0, 0);

