// @generated by protoc-gen-es v1.3.0
// @generated from file spec/messages.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message spec.Message
 */
export const Message = proto3.makeMessageType(
  "spec.Message",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "inner", kind: "message", T: Message_Inner },
    { no: 3, name: "within_inner", kind: "message", T: Message_Inner_WithinInner },
    { no: 4, name: "self", kind: "message", T: Message },
    { no: 5, name: "selfs", kind: "message", T: Message, repeated: true },
    { no: 6, name: "self_map", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Message} },
  ],
);

/**
 * @generated from message spec.Message.Inner
 */
export const Message_Inner = proto3.makeMessageType(
  "spec.Message.Inner",
  () => [
    { no: 1, name: "mess", kind: "message", T: Message, opt: true },
  ],
  {localName: "Message_Inner"},
);

/**
 * @generated from message spec.Message.Inner.WithinInner
 */
export const Message_Inner_WithinInner = proto3.makeMessageType(
  "spec.Message.Inner.WithinInner",
  () => [
    { no: 1, name: "fl", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ],
  {localName: "Message_Inner_WithinInner"},
);

