// @generated by protoc-gen-knit-ts v0.0.7 with parameter "target=dts"
// @generated from file spec/messages.proto (package spec, syntax proto3)
/* eslint-disable */

export interface Message {
    id: string;
    inner?: Message_Inner;
    withinInner?: Message_Inner_WithinInner;
    self?: Message;
    selfs: Array<Message>;
    selfMap: {
        "@map": {
            [k: string]: Message;
        };
    };
}
export interface Message_Inner {
    mess?: Message;
}
export interface Message_Inner_WithinInner {
    fl: number;
}
