// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/messages.proto (package spec, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file spec/messages.proto.
 */
export declare const file_spec_messages: GenFile;

/**
 * @generated from message spec.Message
 */
export declare type Message = Message$1<"spec.Message"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: spec.Message.Inner inner = 2;
   */
  inner?: Message_Inner | undefined;

  /**
   * @generated from field: spec.Message.Inner.WithinInner within_inner = 3;
   */
  withinInner?: Message_Inner_WithinInner | undefined;

  /**
   * @generated from field: spec.Message self = 4;
   */
  self?: Message | undefined;

  /**
   * @generated from field: repeated spec.Message selfs = 5;
   */
  selfs: Message[];

  /**
   * @generated from field: map<string, spec.Message> self_map = 6;
   */
  selfMap: { [key: string]: Message };
};

/**
 * Describes the message spec.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export declare const MessageSchema: GenMessage<Message>;

/**
 * @generated from message spec.Message.Inner
 */
export declare type Message_Inner = Message$1<"spec.Message.Inner"> & {
  /**
   * @generated from field: optional spec.Message mess = 1;
   */
  mess?: Message | undefined;
};

/**
 * Describes the message spec.Message.Inner.
 * Use `create(Message_InnerSchema)` to create a new message.
 */
export declare const Message_InnerSchema: GenMessage<Message_Inner>;

/**
 * @generated from message spec.Message.Inner.WithinInner
 */
export declare type Message_Inner_WithinInner = Message$1<"spec.Message.Inner.WithinInner"> & {
  /**
   * @generated from field: float fl = 1;
   */
  fl: number;
};

/**
 * Describes the message spec.Message.Inner.WithinInner.
 * Use `create(Message_Inner_WithinInnerSchema)` to create a new message.
 */
export declare const Message_Inner_WithinInnerSchema: GenMessage<Message_Inner_WithinInner>;

