// @generated by protoc-gen-es v1.2.0
// @generated from file spec/oneof.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum spec.OneofEnum
 */
export const OneofEnum = proto3.makeEnum(
  "spec.OneofEnum",
  [
    {no: 0, name: "ONEOF_ENUM_ZERO", localName: "ZERO"},
    {no: 1, name: "ONEOF_ENUM_TWO", localName: "TWO"},
  ],
);

/**
 * @generated from message spec.Oneof
 */
export const Oneof = proto3.makeMessageType(
  "spec.Oneof",
  () => [
    { no: 1, name: "scalar", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "oneof_value" },
    { no: 2, name: "message", kind: "message", T: OneofMessage, oneof: "oneof_value" },
    { no: 3, name: "enum", kind: "enum", T: proto3.getEnumType(OneofEnum), oneof: "oneof_value" },
  ],
);

/**
 * @generated from message spec.OneofMessage
 */
export const OneofMessage = proto3.makeMessageType(
  "spec.OneofMessage",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

