// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/oneof.proto (package spec, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file spec/oneof.proto.
 */
export const file_spec_oneof = /*@__PURE__*/
  fileDesc("ChBzcGVjL29uZW9mLnByb3RvEgRzcGVjIp4BCgVPbmVvZhIQCgZzY2FsYXIYASABKAlIABIlCgdtZXNzYWdlGAIgASgLMhIuc3BlYy5PbmVvZk1lc3NhZ2VIABIfCgRlbnVtGAMgASgOMg8uc3BlYy5PbmVvZkVudW1IABIsCg1uZXN0ZWRNZXNzYWdlGAQgASgLMhMuc3BlYy5OZXN0ZWRNZXNzYWdlSABCDQoLb25lb2ZfdmFsdWUiGgoMT25lb2ZNZXNzYWdlEgoKAmlkGAEgASgJIjMKDU5lc3RlZE1lc3NhZ2USIgoGbmVzdGVkGAEgASgLMhIuc3BlYy5PbmVvZk1lc3NhZ2UqNAoJT25lb2ZFbnVtEhMKD09ORU9GX0VOVU1fWkVSTxAAEhIKDk9ORU9GX0VOVU1fVFdPEAFiBnByb3RvMw");

/**
 * Describes the message spec.Oneof.
 * Use `create(OneofSchema)` to create a new message.
 */
export const OneofSchema = /*@__PURE__*/
  messageDesc(file_spec_oneof, 0);

/**
 * Describes the message spec.OneofMessage.
 * Use `create(OneofMessageSchema)` to create a new message.
 */
export const OneofMessageSchema = /*@__PURE__*/
  messageDesc(file_spec_oneof, 1);

/**
 * Describes the message spec.NestedMessage.
 * Use `create(NestedMessageSchema)` to create a new message.
 */
export const NestedMessageSchema = /*@__PURE__*/
  messageDesc(file_spec_oneof, 2);

/**
 * Describes the enum spec.OneofEnum.
 */
export const OneofEnumSchema = /*@__PURE__*/
  enumDesc(file_spec_oneof, 0);

/**
 * @generated from enum spec.OneofEnum
 */
export const OneofEnum = /*@__PURE__*/
  tsEnum(OneofEnumSchema);

