// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/oneof.proto (package spec, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spec/oneof.proto.
 */
export declare const file_spec_oneof: GenFile;

/**
 * @generated from message spec.Oneof
 */
export declare type Oneof = Message<"spec.Oneof"> & {
  /**
   * @generated from oneof spec.Oneof.oneof_value
   */
  oneofValue: {
    /**
     * @generated from field: string scalar = 1;
     */
    value: string;
    case: "scalar";
  } | {
    /**
     * @generated from field: spec.OneofMessage message = 2;
     */
    value: OneofMessage;
    case: "message";
  } | {
    /**
     * @generated from field: spec.OneofEnum enum = 3;
     */
    value: OneofEnum;
    case: "enum";
  } | {
    /**
     * @generated from field: spec.NestedMessage nestedMessage = 4;
     */
    value: NestedMessage;
    case: "nestedMessage";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message spec.Oneof.
 * Use `create(OneofSchema)` to create a new message.
 */
export declare const OneofSchema: GenMessage<Oneof>;

/**
 * @generated from message spec.OneofMessage
 */
export declare type OneofMessage = Message<"spec.OneofMessage"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message spec.OneofMessage.
 * Use `create(OneofMessageSchema)` to create a new message.
 */
export declare const OneofMessageSchema: GenMessage<OneofMessage>;

/**
 * @generated from message spec.NestedMessage
 */
export declare type NestedMessage = Message<"spec.NestedMessage"> & {
  /**
   * @generated from field: spec.OneofMessage nested = 1;
   */
  nested?: OneofMessage | undefined;
};

/**
 * Describes the message spec.NestedMessage.
 * Use `create(NestedMessageSchema)` to create a new message.
 */
export declare const NestedMessageSchema: GenMessage<NestedMessage>;

/**
 * @generated from enum spec.OneofEnum
 */
export enum OneofEnum {
  /**
   * @generated from enum value: ONEOF_ENUM_ZERO = 0;
   */
  ZERO = 0,

  /**
   * @generated from enum value: ONEOF_ENUM_TWO = 1;
   */
  TWO = 1,
}

/**
 * Describes the enum spec.OneofEnum.
 */
export declare const OneofEnumSchema: GenEnum<OneofEnum>;

