// @generated by protoc-gen-knit-ts v0.0.7 with parameter "target=dts"
// @generated from file spec/oneof.proto (package spec, syntax proto3)
/* eslint-disable */

export interface Oneof {
    oneofValue?: {
        "@oneof": {
            scalar: string;
            message: OneofMessage;
            enum: {
                "@enum": OneofEnum;
            };
            nestedMessage: NestedMessage;
        };
    };
}
export interface OneofMessage {
    id: string;
}
export interface NestedMessage {
    nested?: OneofMessage;
}
export type OneofEnum = "ONEOF_ENUM_ZERO" | "ONEOF_ENUM_TWO" | number;
