// @generated by protoc-gen-knit-ts v0.0.3
// @generated from file spec/proto2.proto (package spec, syntax proto2)
/* eslint-disable */
// @ts-nocheck

export interface Proto2Message {
    requiredField: number;
    optionalField?: number;
    enum?: {
        "@enum": Proto2Enum;
    };
    child?: Proto2Child;
}
export interface Proto2Child {
    id?: string;
}
export declare type Proto2Enum = "UNSPECIFIED" | "SOMETHING" | number;
