// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/proto2.proto (package spec, syntax proto2)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file spec/proto2.proto.
 */
export const file_spec_proto2 = /*@__PURE__*/
  fileDesc("ChFzcGVjL3Byb3RvMi5wcm90bxIEc3BlYyKBAQoNUHJvdG8yTWVzc2FnZRIWCg5yZXF1aXJlZF9maWVsZBgBIAIoBRIWCg5vcHRpb25hbF9maWVsZBgCIAEoDRIeCgRlbnVtGAMgASgOMhAuc3BlYy5Qcm90bzJFbnVtEiAKBWNoaWxkGAQgASgLMhEuc3BlYy5Qcm90bzJDaGlsZCIZCgtQcm90bzJDaGlsZBIKCgJpZBgBIAEoCSosCgpQcm90bzJFbnVtEg8KC1VOU1BFQ0lGSUVEEAESDQoJU09NRVRISU5HEAI");

/**
 * Describes the message spec.Proto2Message.
 * Use `create(Proto2MessageSchema)` to create a new message.
 */
export const Proto2MessageSchema = /*@__PURE__*/
  messageDesc(file_spec_proto2, 0);

/**
 * Describes the message spec.Proto2Child.
 * Use `create(Proto2ChildSchema)` to create a new message.
 */
export const Proto2ChildSchema = /*@__PURE__*/
  messageDesc(file_spec_proto2, 1);

/**
 * Describes the enum spec.Proto2Enum.
 */
export const Proto2EnumSchema = /*@__PURE__*/
  enumDesc(file_spec_proto2, 0);

/**
 * @generated from enum spec.Proto2Enum
 */
export const Proto2Enum = /*@__PURE__*/
  tsEnum(Proto2EnumSchema);

