// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/proto2.proto (package spec, syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spec/proto2.proto.
 */
export declare const file_spec_proto2: GenFile;

/**
 * @generated from message spec.Proto2Message
 */
export declare type Proto2Message = Message<"spec.Proto2Message"> & {
  /**
   * @generated from field: required int32 required_field = 1;
   */
  requiredField: number;

  /**
   * @generated from field: optional uint32 optional_field = 2;
   */
  optionalField: number;

  /**
   * @generated from field: optional spec.Proto2Enum enum = 3;
   */
  enum: Proto2Enum;

  /**
   * @generated from field: optional spec.Proto2Child child = 4;
   */
  child?: Proto2Child | undefined;
};

/**
 * Describes the message spec.Proto2Message.
 * Use `create(Proto2MessageSchema)` to create a new message.
 */
export declare const Proto2MessageSchema: GenMessage<Proto2Message>;

/**
 * @generated from message spec.Proto2Child
 */
export declare type Proto2Child = Message<"spec.Proto2Child"> & {
  /**
   * @generated from field: optional string id = 1;
   */
  id: string;
};

/**
 * Describes the message spec.Proto2Child.
 * Use `create(Proto2ChildSchema)` to create a new message.
 */
export declare const Proto2ChildSchema: GenMessage<Proto2Child>;

/**
 * @generated from enum spec.Proto2Enum
 */
export enum Proto2Enum {
  /**
   * @generated from enum value: UNSPECIFIED = 1;
   */
  UNSPECIFIED = 1,

  /**
   * @generated from enum value: SOMETHING = 2;
   */
  SOMETHING = 2,
}

/**
 * Describes the enum spec.Proto2Enum.
 */
export declare const Proto2EnumSchema: GenEnum<Proto2Enum>;

