// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/relations.proto (package spec, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_knit_v1alpha1_options } from "../buf/knit/v1alpha1/options_pb.js";
import { file_spec_all } from "./all_pb.js";

/**
 * Describes the file spec/relations.proto.
 */
export const file_spec_relations = /*@__PURE__*/
  fileDesc("ChRzcGVjL3JlbGF0aW9ucy5wcm90bxIEc3BlYyIwChRHZXRBbGxSZWxTZWxmUmVxdWVzdBIYCgViYXNlcxgBIAMoCzIJLnNwZWMuQWxsIngKFUdldEFsbFJlbFNlbGZSZXNwb25zZRI1CgZ2YWx1ZXMYASADKAsyJS5zcGVjLkdldEFsbFJlbFNlbGZSZXNwb25zZS5BbGxSZXN1bHQaKAoJQWxsUmVzdWx0EhsKCHJlbF9zZWxmGAEgASgLMgkuc3BlYy5BbGwiQQoZR2V0QWxsUmVsU2VsZlBhcmFtUmVxdWVzdBIYCgViYXNlcxgBIAMoCzIJLnNwZWMuQWxsEgoKAmlkGAIgASgJIpIBChpHZXRBbGxSZWxTZWxmUGFyYW1SZXNwb25zZRI/CgZ2YWx1ZXMYASADKAsyLy5zcGVjLkdldEFsbFJlbFNlbGZQYXJhbVJlc3BvbnNlLkFsbFBhcmFtUmVzdWx0GjMKDkFsbFBhcmFtUmVzdWx0EiEKDnJlbF9zZWxmX3BhcmFtGAEgASgLMgkuc3BlYy5BbGwy2wEKEkFsbFJlc29sdmVyU2VydmljZRJXCg1HZXRBbGxSZWxTZWxmEhouc3BlYy5HZXRBbGxSZWxTZWxmUmVxdWVzdBobLnNwZWMuR2V0QWxsUmVsU2VsZlJlc3BvbnNlIg2qSAoKCHJlbF9zZWxmEmwKEkdldEFsbFJlbFNlbGZQYXJhbRIfLnNwZWMuR2V0QWxsUmVsU2VsZlBhcmFtUmVxdWVzdBogLnNwZWMuR2V0QWxsUmVsU2VsZlBhcmFtUmVzcG9uc2UiE6pIEAoOcmVsX3NlbGZfcGFyYW1iBnByb3RvMw", [file_buf_knit_v1alpha1_options, file_spec_all]);

/**
 * Describes the message spec.GetAllRelSelfRequest.
 * Use `create(GetAllRelSelfRequestSchema)` to create a new message.
 */
export const GetAllRelSelfRequestSchema = /*@__PURE__*/
  messageDesc(file_spec_relations, 0);

/**
 * Describes the message spec.GetAllRelSelfResponse.
 * Use `create(GetAllRelSelfResponseSchema)` to create a new message.
 */
export const GetAllRelSelfResponseSchema = /*@__PURE__*/
  messageDesc(file_spec_relations, 1);

/**
 * Describes the message spec.GetAllRelSelfResponse.AllResult.
 * Use `create(GetAllRelSelfResponse_AllResultSchema)` to create a new message.
 */
export const GetAllRelSelfResponse_AllResultSchema = /*@__PURE__*/
  messageDesc(file_spec_relations, 1, 0);

/**
 * Describes the message spec.GetAllRelSelfParamRequest.
 * Use `create(GetAllRelSelfParamRequestSchema)` to create a new message.
 */
export const GetAllRelSelfParamRequestSchema = /*@__PURE__*/
  messageDesc(file_spec_relations, 2);

/**
 * Describes the message spec.GetAllRelSelfParamResponse.
 * Use `create(GetAllRelSelfParamResponseSchema)` to create a new message.
 */
export const GetAllRelSelfParamResponseSchema = /*@__PURE__*/
  messageDesc(file_spec_relations, 3);

/**
 * Describes the message spec.GetAllRelSelfParamResponse.AllParamResult.
 * Use `create(GetAllRelSelfParamResponse_AllParamResultSchema)` to create a new message.
 */
export const GetAllRelSelfParamResponse_AllParamResultSchema = /*@__PURE__*/
  messageDesc(file_spec_relations, 3, 0);

/**
 * @generated from service spec.AllResolverService
 */
export const AllResolverService = /*@__PURE__*/
  serviceDesc(file_spec_relations, 0);

