// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/relations.proto (package spec, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { All } from "./all_pb.js";

/**
 * Describes the file spec/relations.proto.
 */
export declare const file_spec_relations: GenFile;

/**
 * @generated from message spec.GetAllRelSelfRequest
 */
export declare type GetAllRelSelfRequest = Message<"spec.GetAllRelSelfRequest"> & {
  /**
   * @generated from field: repeated spec.All bases = 1;
   */
  bases: All[];
};

/**
 * Describes the message spec.GetAllRelSelfRequest.
 * Use `create(GetAllRelSelfRequestSchema)` to create a new message.
 */
export declare const GetAllRelSelfRequestSchema: GenMessage<GetAllRelSelfRequest>;

/**
 * @generated from message spec.GetAllRelSelfResponse
 */
export declare type GetAllRelSelfResponse = Message<"spec.GetAllRelSelfResponse"> & {
  /**
   * @generated from field: repeated spec.GetAllRelSelfResponse.AllResult values = 1;
   */
  values: GetAllRelSelfResponse_AllResult[];
};

/**
 * Describes the message spec.GetAllRelSelfResponse.
 * Use `create(GetAllRelSelfResponseSchema)` to create a new message.
 */
export declare const GetAllRelSelfResponseSchema: GenMessage<GetAllRelSelfResponse>;

/**
 * @generated from message spec.GetAllRelSelfResponse.AllResult
 */
export declare type GetAllRelSelfResponse_AllResult = Message<"spec.GetAllRelSelfResponse.AllResult"> & {
  /**
   * @generated from field: spec.All rel_self = 1;
   */
  relSelf?: All | undefined;
};

/**
 * Describes the message spec.GetAllRelSelfResponse.AllResult.
 * Use `create(GetAllRelSelfResponse_AllResultSchema)` to create a new message.
 */
export declare const GetAllRelSelfResponse_AllResultSchema: GenMessage<GetAllRelSelfResponse_AllResult>;

/**
 * @generated from message spec.GetAllRelSelfParamRequest
 */
export declare type GetAllRelSelfParamRequest = Message<"spec.GetAllRelSelfParamRequest"> & {
  /**
   * @generated from field: repeated spec.All bases = 1;
   */
  bases: All[];

  /**
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * Describes the message spec.GetAllRelSelfParamRequest.
 * Use `create(GetAllRelSelfParamRequestSchema)` to create a new message.
 */
export declare const GetAllRelSelfParamRequestSchema: GenMessage<GetAllRelSelfParamRequest>;

/**
 * @generated from message spec.GetAllRelSelfParamResponse
 */
export declare type GetAllRelSelfParamResponse = Message<"spec.GetAllRelSelfParamResponse"> & {
  /**
   * @generated from field: repeated spec.GetAllRelSelfParamResponse.AllParamResult values = 1;
   */
  values: GetAllRelSelfParamResponse_AllParamResult[];
};

/**
 * Describes the message spec.GetAllRelSelfParamResponse.
 * Use `create(GetAllRelSelfParamResponseSchema)` to create a new message.
 */
export declare const GetAllRelSelfParamResponseSchema: GenMessage<GetAllRelSelfParamResponse>;

/**
 * @generated from message spec.GetAllRelSelfParamResponse.AllParamResult
 */
export declare type GetAllRelSelfParamResponse_AllParamResult = Message<"spec.GetAllRelSelfParamResponse.AllParamResult"> & {
  /**
   * @generated from field: spec.All rel_self_param = 1;
   */
  relSelfParam?: All | undefined;
};

/**
 * Describes the message spec.GetAllRelSelfParamResponse.AllParamResult.
 * Use `create(GetAllRelSelfParamResponse_AllParamResultSchema)` to create a new message.
 */
export declare const GetAllRelSelfParamResponse_AllParamResultSchema: GenMessage<GetAllRelSelfParamResponse_AllParamResult>;

/**
 * @generated from service spec.AllResolverService
 */
export declare const AllResolverService: GenService<{
  /**
   * @generated from rpc spec.AllResolverService.GetAllRelSelf
   */
  getAllRelSelf: {
    methodKind: "unary";
    input: typeof GetAllRelSelfRequestSchema;
    output: typeof GetAllRelSelfResponseSchema;
  },
  /**
   * @generated from rpc spec.AllResolverService.GetAllRelSelfParam
   */
  getAllRelSelfParam: {
    methodKind: "unary";
    input: typeof GetAllRelSelfParamRequestSchema;
    output: typeof GetAllRelSelfParamResponseSchema;
  },
}>;

