// @generated by protoc-gen-es v1.5.0
// @generated from file spec/relations.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { All } from "./all_pb.js";

/**
 * @generated from message spec.GetAllRelSelfRequest
 */
export declare class GetAllRelSelfRequest extends Message<GetAllRelSelfRequest> {
  /**
   * @generated from field: repeated spec.All bases = 1;
   */
  bases: All[];

  constructor(data?: PartialMessage<GetAllRelSelfRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "spec.GetAllRelSelfRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllRelSelfRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllRelSelfRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllRelSelfRequest;

  static equals(a: GetAllRelSelfRequest | PlainMessage<GetAllRelSelfRequest> | undefined, b: GetAllRelSelfRequest | PlainMessage<GetAllRelSelfRequest> | undefined): boolean;
}

/**
 * @generated from message spec.GetAllRelSelfResponse
 */
export declare class GetAllRelSelfResponse extends Message<GetAllRelSelfResponse> {
  /**
   * @generated from field: repeated spec.GetAllRelSelfResponse.AllResult values = 1;
   */
  values: GetAllRelSelfResponse_AllResult[];

  constructor(data?: PartialMessage<GetAllRelSelfResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "spec.GetAllRelSelfResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllRelSelfResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllRelSelfResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllRelSelfResponse;

  static equals(a: GetAllRelSelfResponse | PlainMessage<GetAllRelSelfResponse> | undefined, b: GetAllRelSelfResponse | PlainMessage<GetAllRelSelfResponse> | undefined): boolean;
}

/**
 * @generated from message spec.GetAllRelSelfResponse.AllResult
 */
export declare class GetAllRelSelfResponse_AllResult extends Message<GetAllRelSelfResponse_AllResult> {
  /**
   * @generated from field: spec.All rel_self = 1;
   */
  relSelf?: All;

  constructor(data?: PartialMessage<GetAllRelSelfResponse_AllResult>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "spec.GetAllRelSelfResponse.AllResult";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllRelSelfResponse_AllResult;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllRelSelfResponse_AllResult;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllRelSelfResponse_AllResult;

  static equals(a: GetAllRelSelfResponse_AllResult | PlainMessage<GetAllRelSelfResponse_AllResult> | undefined, b: GetAllRelSelfResponse_AllResult | PlainMessage<GetAllRelSelfResponse_AllResult> | undefined): boolean;
}

/**
 * @generated from message spec.GetAllRelSelfParamRequest
 */
export declare class GetAllRelSelfParamRequest extends Message<GetAllRelSelfParamRequest> {
  /**
   * @generated from field: repeated spec.All bases = 1;
   */
  bases: All[];

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  constructor(data?: PartialMessage<GetAllRelSelfParamRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "spec.GetAllRelSelfParamRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllRelSelfParamRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllRelSelfParamRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllRelSelfParamRequest;

  static equals(a: GetAllRelSelfParamRequest | PlainMessage<GetAllRelSelfParamRequest> | undefined, b: GetAllRelSelfParamRequest | PlainMessage<GetAllRelSelfParamRequest> | undefined): boolean;
}

/**
 * @generated from message spec.GetAllRelSelfParamResponse
 */
export declare class GetAllRelSelfParamResponse extends Message<GetAllRelSelfParamResponse> {
  /**
   * @generated from field: repeated spec.GetAllRelSelfParamResponse.AllParamResult values = 1;
   */
  values: GetAllRelSelfParamResponse_AllParamResult[];

  constructor(data?: PartialMessage<GetAllRelSelfParamResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "spec.GetAllRelSelfParamResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllRelSelfParamResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllRelSelfParamResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllRelSelfParamResponse;

  static equals(a: GetAllRelSelfParamResponse | PlainMessage<GetAllRelSelfParamResponse> | undefined, b: GetAllRelSelfParamResponse | PlainMessage<GetAllRelSelfParamResponse> | undefined): boolean;
}

/**
 * @generated from message spec.GetAllRelSelfParamResponse.AllParamResult
 */
export declare class GetAllRelSelfParamResponse_AllParamResult extends Message<GetAllRelSelfParamResponse_AllParamResult> {
  /**
   * @generated from field: spec.All rel_self_param = 1;
   */
  relSelfParam?: All;

  constructor(data?: PartialMessage<GetAllRelSelfParamResponse_AllParamResult>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "spec.GetAllRelSelfParamResponse.AllParamResult";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllRelSelfParamResponse_AllParamResult;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllRelSelfParamResponse_AllParamResult;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllRelSelfParamResponse_AllParamResult;

  static equals(a: GetAllRelSelfParamResponse_AllParamResult | PlainMessage<GetAllRelSelfParamResponse_AllParamResult> | undefined, b: GetAllRelSelfParamResponse_AllParamResult | PlainMessage<GetAllRelSelfParamResponse_AllParamResult> | undefined): boolean;
}

