// @generated by protoc-gen-connect-es v0.8.6
// @generated from file spec/relations.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetAllRelSelfParamRequest, GetAllRelSelfParamResponse, GetAllRelSelfRequest, GetAllRelSelfResponse } from "./relations_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service spec.AllResolverService
 */
export const AllResolverService = {
  typeName: "spec.AllResolverService",
  methods: {
    /**
     * @generated from rpc spec.AllResolverService.GetAllRelSelf
     */
    getAllRelSelf: {
      name: "GetAllRelSelf",
      I: GetAllRelSelfRequest,
      O: GetAllRelSelfResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.AllResolverService.GetAllRelSelfParam
     */
    getAllRelSelfParam: {
      name: "GetAllRelSelfParam",
      I: GetAllRelSelfParamRequest,
      O: GetAllRelSelfParamResponse,
      kind: MethodKind.Unary,
    },
  }
};

