// @generated by protoc-gen-connect-es v0.8.6
// @generated from file spec/wkt.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Any, BoolValue, BytesValue, DoubleValue, Duration, Empty, FieldMask, FloatValue, Int32Value, Int64Value, ListValue, MethodKind, StringValue, Struct, Timestamp, UInt32Value, UInt64Value, Value } from "@bufbuild/protobuf";

/**
 * @generated from service spec.WktService
 */
export declare const WktService: {
  readonly typeName: "spec.WktService",
  readonly methods: {
    /**
     * @generated from rpc spec.WktService.GetDoubleValue
     */
    readonly getDoubleValue: {
      readonly name: "GetDoubleValue",
      readonly I: typeof DoubleValue,
      readonly O: typeof DoubleValue,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetBoolValue
     */
    readonly getBoolValue: {
      readonly name: "GetBoolValue",
      readonly I: typeof BoolValue,
      readonly O: typeof BoolValue,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetFloatValue
     */
    readonly getFloatValue: {
      readonly name: "GetFloatValue",
      readonly I: typeof FloatValue,
      readonly O: typeof FloatValue,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetInt64Value
     */
    readonly getInt64Value: {
      readonly name: "GetInt64Value",
      readonly I: typeof Int64Value,
      readonly O: typeof Int64Value,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetUint64Value
     */
    readonly getUint64Value: {
      readonly name: "GetUint64Value",
      readonly I: typeof UInt64Value,
      readonly O: typeof UInt64Value,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetInt32Value
     */
    readonly getInt32Value: {
      readonly name: "GetInt32Value",
      readonly I: typeof Int32Value,
      readonly O: typeof Int32Value,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetUint32Value
     */
    readonly getUint32Value: {
      readonly name: "GetUint32Value",
      readonly I: typeof UInt32Value,
      readonly O: typeof UInt32Value,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetStringValue
     */
    readonly getStringValue: {
      readonly name: "GetStringValue",
      readonly I: typeof StringValue,
      readonly O: typeof StringValue,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetBytesValue
     */
    readonly getBytesValue: {
      readonly name: "GetBytesValue",
      readonly I: typeof BytesValue,
      readonly O: typeof BytesValue,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetAny
     */
    readonly getAny: {
      readonly name: "GetAny",
      readonly I: typeof Any,
      readonly O: typeof Any,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetDuration
     */
    readonly getDuration: {
      readonly name: "GetDuration",
      readonly I: typeof Duration,
      readonly O: typeof Duration,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetEmpty
     */
    readonly getEmpty: {
      readonly name: "GetEmpty",
      readonly I: typeof Empty,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetFieldMask
     */
    readonly getFieldMask: {
      readonly name: "GetFieldMask",
      readonly I: typeof FieldMask,
      readonly O: typeof FieldMask,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetTimestamp
     */
    readonly getTimestamp: {
      readonly name: "GetTimestamp",
      readonly I: typeof Timestamp,
      readonly O: typeof Timestamp,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetStruct
     */
    readonly getStruct: {
      readonly name: "GetStruct",
      readonly I: typeof Struct,
      readonly O: typeof Struct,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetListValue
     */
    readonly getListValue: {
      readonly name: "GetListValue",
      readonly I: typeof ListValue,
      readonly O: typeof ListValue,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetValue
     */
    readonly getValue: {
      readonly name: "GetValue",
      readonly I: typeof Value,
      readonly O: typeof Value,
      readonly kind: MethodKind.Unary,
    },
  }
};

