// @generated by protoc-gen-connect-es v0.13.1
// @generated from file spec/wkt.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Any, BoolValue, BytesValue, DoubleValue, Duration, Empty, FieldMask, FloatValue, Int32Value, Int64Value, ListValue, MethodKind, StringValue, Struct, Timestamp, UInt32Value, UInt64Value, Value } from "@bufbuild/protobuf";

/**
 * @generated from service spec.WktService
 */
export const WktService = {
  typeName: "spec.WktService",
  methods: {
    /**
     * @generated from rpc spec.WktService.GetDoubleValue
     */
    getDoubleValue: {
      name: "GetDoubleValue",
      I: DoubleValue,
      O: DoubleValue,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetBoolValue
     */
    getBoolValue: {
      name: "GetBoolValue",
      I: BoolValue,
      O: BoolValue,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetFloatValue
     */
    getFloatValue: {
      name: "GetFloatValue",
      I: FloatValue,
      O: FloatValue,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetInt64Value
     */
    getInt64Value: {
      name: "GetInt64Value",
      I: Int64Value,
      O: Int64Value,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetUint64Value
     */
    getUint64Value: {
      name: "GetUint64Value",
      I: UInt64Value,
      O: UInt64Value,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetInt32Value
     */
    getInt32Value: {
      name: "GetInt32Value",
      I: Int32Value,
      O: Int32Value,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetUint32Value
     */
    getUint32Value: {
      name: "GetUint32Value",
      I: UInt32Value,
      O: UInt32Value,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetStringValue
     */
    getStringValue: {
      name: "GetStringValue",
      I: StringValue,
      O: StringValue,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetBytesValue
     */
    getBytesValue: {
      name: "GetBytesValue",
      I: BytesValue,
      O: BytesValue,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetAny
     */
    getAny: {
      name: "GetAny",
      I: Any,
      O: Any,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetDuration
     */
    getDuration: {
      name: "GetDuration",
      I: Duration,
      O: Duration,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetEmpty
     */
    getEmpty: {
      name: "GetEmpty",
      I: Empty,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetFieldMask
     */
    getFieldMask: {
      name: "GetFieldMask",
      I: FieldMask,
      O: FieldMask,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetTimestamp
     */
    getTimestamp: {
      name: "GetTimestamp",
      I: Timestamp,
      O: Timestamp,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetStruct
     */
    getStruct: {
      name: "GetStruct",
      I: Struct,
      O: Struct,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetListValue
     */
    getListValue: {
      name: "GetListValue",
      I: ListValue,
      O: ListValue,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.WktService.GetValue
     */
    getValue: {
      name: "GetValue",
      I: Value,
      O: Value,
      kind: MethodKind.Unary,
    },
  }
};

