// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/wkt.proto (package spec, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { Any, AnySchema, BoolValue, BoolValueSchema, BytesValue, BytesValueSchema, DoubleValue, DoubleValueSchema, Duration, DurationSchema, Empty, EmptySchema, FieldMask, FieldMaskSchema, FloatValue, FloatValueSchema, Int32Value, Int32ValueSchema, Int64Value, Int64ValueSchema, ListValue, ListValueSchema, NullValue, StringValue, StringValueSchema, StructSchema, Timestamp, TimestampSchema, UInt32Value, UInt32ValueSchema, UInt64Value, UInt64ValueSchema, Value, ValueSchema } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file spec/wkt.proto.
 */
export declare const file_spec_wkt: GenFile;

/**
 * @generated from message spec.Wkt
 */
export declare type Wkt = Message<"spec.Wkt"> & {
  /**
   * @generated from field: spec.WktFields fields = 1;
   */
  fields?: WktFields | undefined;

  /**
   * @generated from field: spec.WktOneof oneofs = 2;
   */
  oneofs?: WktOneof | undefined;

  /**
   * @generated from field: spec.WktMap maps = 3;
   */
  maps?: WktMap | undefined;

  /**
   * @generated from field: spec.WktRepeated repeated = 4;
   */
  repeated?: WktRepeated | undefined;
};

/**
 * Describes the message spec.Wkt.
 * Use `create(WktSchema)` to create a new message.
 */
export declare const WktSchema: GenMessage<Wkt>;

/**
 * @generated from message spec.WktFields
 */
export declare type WktFields = Message<"spec.WktFields"> & {
  /**
   * @generated from field: google.protobuf.DoubleValue double_value = 1;
   */
  doubleValue?: number | undefined;

  /**
   * @generated from field: google.protobuf.BoolValue bool_value = 2;
   */
  boolValue?: boolean | undefined;

  /**
   * @generated from field: google.protobuf.FloatValue float_value = 3;
   */
  floatValue?: number | undefined;

  /**
   * @generated from field: google.protobuf.Int64Value int64_value = 4;
   */
  int64Value?: bigint | undefined;

  /**
   * @generated from field: google.protobuf.UInt64Value uint64_value = 5;
   */
  uint64Value?: bigint | undefined;

  /**
   * @generated from field: google.protobuf.Int32Value int32_value = 6;
   */
  int32Value?: number | undefined;

  /**
   * @generated from field: google.protobuf.UInt32Value uint32_value = 7;
   */
  uint32Value?: number | undefined;

  /**
   * @generated from field: google.protobuf.StringValue string_value = 8;
   */
  stringValue?: string | undefined;

  /**
   * @generated from field: google.protobuf.BytesValue bytes_value = 9;
   */
  bytesValue?: Uint8Array | undefined;

  /**
   * @generated from field: google.protobuf.Any any = 10;
   */
  any?: Any | undefined;

  /**
   * @generated from field: google.protobuf.Duration duration = 11;
   */
  duration?: Duration | undefined;

  /**
   * @generated from field: google.protobuf.Empty empty = 12;
   */
  empty?: Empty | undefined;

  /**
   * @generated from field: google.protobuf.FieldMask field_mask = 13;
   */
  fieldMask?: FieldMask | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 14;
   */
  timestamp?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Struct struct = 15;
   */
  struct?: JsonObject | undefined;

  /**
   * @generated from field: google.protobuf.ListValue list_value = 16;
   */
  listValue?: ListValue | undefined;

  /**
   * @generated from field: google.protobuf.Value value = 17;
   */
  value?: Value | undefined;

  /**
   * @generated from field: google.protobuf.NullValue null_value = 18;
   */
  nullValue: NullValue;
};

/**
 * Describes the message spec.WktFields.
 * Use `create(WktFieldsSchema)` to create a new message.
 */
export declare const WktFieldsSchema: GenMessage<WktFields>;

/**
 * @generated from message spec.WktOneof
 */
export declare type WktOneof = Message<"spec.WktOneof"> & {
  /**
   * @generated from oneof spec.WktOneof.oneof_value
   */
  oneofValue: {
    /**
     * @generated from field: google.protobuf.DoubleValue double_value = 1;
     */
    value: DoubleValue;
    case: "doubleValue";
  } | {
    /**
     * @generated from field: google.protobuf.BoolValue bool_value = 2;
     */
    value: BoolValue;
    case: "boolValue";
  } | {
    /**
     * @generated from field: google.protobuf.FloatValue float_value = 3;
     */
    value: FloatValue;
    case: "floatValue";
  } | {
    /**
     * @generated from field: google.protobuf.Int64Value int64_value = 4;
     */
    value: Int64Value;
    case: "int64Value";
  } | {
    /**
     * @generated from field: google.protobuf.UInt64Value uint64_value = 5;
     */
    value: UInt64Value;
    case: "uint64Value";
  } | {
    /**
     * @generated from field: google.protobuf.Int32Value int32_value = 6;
     */
    value: Int32Value;
    case: "int32Value";
  } | {
    /**
     * @generated from field: google.protobuf.UInt32Value uint32_value = 7;
     */
    value: UInt32Value;
    case: "uint32Value";
  } | {
    /**
     * @generated from field: google.protobuf.StringValue string_value = 8;
     */
    value: StringValue;
    case: "stringValue";
  } | {
    /**
     * @generated from field: google.protobuf.BytesValue bytes_value = 9;
     */
    value: BytesValue;
    case: "bytesValue";
  } | {
    /**
     * @generated from field: google.protobuf.Any any = 10;
     */
    value: Any;
    case: "any";
  } | {
    /**
     * @generated from field: google.protobuf.Duration duration = 11;
     */
    value: Duration;
    case: "duration";
  } | {
    /**
     * @generated from field: google.protobuf.Empty empty = 12;
     */
    value: Empty;
    case: "empty";
  } | {
    /**
     * @generated from field: google.protobuf.FieldMask field_mask = 13;
     */
    value: FieldMask;
    case: "fieldMask";
  } | {
    /**
     * @generated from field: google.protobuf.Timestamp timestamp = 14;
     */
    value: Timestamp;
    case: "timestamp";
  } | {
    /**
     * @generated from field: google.protobuf.Struct struct = 15;
     */
    value: JsonObject;
    case: "struct";
  } | {
    /**
     * @generated from field: google.protobuf.ListValue list_value = 16;
     */
    value: ListValue;
    case: "listValue";
  } | {
    /**
     * @generated from field: google.protobuf.Value value = 17;
     */
    value: Value;
    case: "value";
  } | {
    /**
     * @generated from field: google.protobuf.NullValue null_value = 18;
     */
    value: NullValue;
    case: "nullValue";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message spec.WktOneof.
 * Use `create(WktOneofSchema)` to create a new message.
 */
export declare const WktOneofSchema: GenMessage<WktOneof>;

/**
 * @generated from message spec.WktMap
 */
export declare type WktMap = Message<"spec.WktMap"> & {
  /**
   * @generated from field: map<string, google.protobuf.DoubleValue> double_value = 1;
   */
  doubleValue: { [key: string]: DoubleValue };

  /**
   * @generated from field: map<string, google.protobuf.BoolValue> bool_value = 2;
   */
  boolValue: { [key: string]: BoolValue };

  /**
   * @generated from field: map<string, google.protobuf.FloatValue> float_value = 3;
   */
  floatValue: { [key: string]: FloatValue };

  /**
   * @generated from field: map<string, google.protobuf.Int64Value> int64_value = 4;
   */
  int64Value: { [key: string]: Int64Value };

  /**
   * @generated from field: map<string, google.protobuf.UInt64Value> uint64_value = 5;
   */
  uint64Value: { [key: string]: UInt64Value };

  /**
   * @generated from field: map<string, google.protobuf.Int32Value> int32_value = 6;
   */
  int32Value: { [key: string]: Int32Value };

  /**
   * @generated from field: map<string, google.protobuf.UInt32Value> uint32_value = 7;
   */
  uint32Value: { [key: string]: UInt32Value };

  /**
   * @generated from field: map<string, google.protobuf.StringValue> string_value = 8;
   */
  stringValue: { [key: string]: StringValue };

  /**
   * @generated from field: map<string, google.protobuf.BytesValue> bytes_value = 9;
   */
  bytesValue: { [key: string]: BytesValue };

  /**
   * @generated from field: map<string, google.protobuf.Any> any = 10;
   */
  any: { [key: string]: Any };

  /**
   * @generated from field: map<string, google.protobuf.Duration> duration = 11;
   */
  duration: { [key: string]: Duration };

  /**
   * @generated from field: map<string, google.protobuf.Empty> empty = 12;
   */
  empty: { [key: string]: Empty };

  /**
   * @generated from field: map<string, google.protobuf.FieldMask> field_mask = 13;
   */
  fieldMask: { [key: string]: FieldMask };

  /**
   * @generated from field: map<string, google.protobuf.Timestamp> timestamp = 14;
   */
  timestamp: { [key: string]: Timestamp };

  /**
   * @generated from field: map<string, google.protobuf.Struct> struct = 15;
   */
  struct: { [key: string]: JsonObject };

  /**
   * @generated from field: map<string, google.protobuf.ListValue> list_value = 16;
   */
  listValue: { [key: string]: ListValue };

  /**
   * @generated from field: map<string, google.protobuf.Value> value = 17;
   */
  value: { [key: string]: Value };

  /**
   * @generated from field: map<string, google.protobuf.NullValue> null_value = 18;
   */
  nullValue: { [key: string]: NullValue };
};

/**
 * Describes the message spec.WktMap.
 * Use `create(WktMapSchema)` to create a new message.
 */
export declare const WktMapSchema: GenMessage<WktMap>;

/**
 * @generated from message spec.WktRepeated
 */
export declare type WktRepeated = Message<"spec.WktRepeated"> & {
  /**
   * @generated from field: repeated google.protobuf.DoubleValue double_value = 1;
   */
  doubleValue: DoubleValue[];

  /**
   * @generated from field: repeated google.protobuf.BoolValue bool_value = 2;
   */
  boolValue: BoolValue[];

  /**
   * @generated from field: repeated google.protobuf.FloatValue float_value = 3;
   */
  floatValue: FloatValue[];

  /**
   * @generated from field: repeated google.protobuf.Int64Value int64_value = 4;
   */
  int64Value: Int64Value[];

  /**
   * @generated from field: repeated google.protobuf.UInt64Value uint64_value = 5;
   */
  uint64Value: UInt64Value[];

  /**
   * @generated from field: repeated google.protobuf.Int32Value int32_value = 6;
   */
  int32Value: Int32Value[];

  /**
   * @generated from field: repeated google.protobuf.UInt32Value uint32_value = 7;
   */
  uint32Value: UInt32Value[];

  /**
   * @generated from field: repeated google.protobuf.StringValue string_value = 8;
   */
  stringValue: StringValue[];

  /**
   * @generated from field: repeated google.protobuf.BytesValue bytes_value = 9;
   */
  bytesValue: BytesValue[];

  /**
   * @generated from field: repeated google.protobuf.Any any = 10;
   */
  any: Any[];

  /**
   * @generated from field: repeated google.protobuf.Duration duration = 11;
   */
  duration: Duration[];

  /**
   * @generated from field: repeated google.protobuf.Empty empty = 12;
   */
  empty: Empty[];

  /**
   * @generated from field: repeated google.protobuf.FieldMask field_mask = 13;
   */
  fieldMask: FieldMask[];

  /**
   * @generated from field: repeated google.protobuf.Timestamp timestamp = 14;
   */
  timestamp: Timestamp[];

  /**
   * @generated from field: repeated google.protobuf.Struct struct = 15;
   */
  struct: JsonObject[];

  /**
   * @generated from field: repeated google.protobuf.ListValue list_value = 16;
   */
  listValue: ListValue[];

  /**
   * @generated from field: repeated google.protobuf.Value value = 17;
   */
  value: Value[];

  /**
   * @generated from field: repeated google.protobuf.NullValue null_value = 18;
   */
  nullValue: NullValue[];
};

/**
 * Describes the message spec.WktRepeated.
 * Use `create(WktRepeatedSchema)` to create a new message.
 */
export declare const WktRepeatedSchema: GenMessage<WktRepeated>;

/**
 * @generated from service spec.WktService
 */
export declare const WktService: GenService<{
  /**
   * @generated from rpc spec.WktService.GetDoubleValue
   */
  getDoubleValue: {
    methodKind: "unary";
    input: typeof DoubleValueSchema;
    output: typeof DoubleValueSchema;
  },
  /**
   * @generated from rpc spec.WktService.GetBoolValue
   */
  getBoolValue: {
    methodKind: "unary";
    input: typeof BoolValueSchema;
    output: typeof BoolValueSchema;
  },
  /**
   * @generated from rpc spec.WktService.GetFloatValue
   */
  getFloatValue: {
    methodKind: "unary";
    input: typeof FloatValueSchema;
    output: typeof FloatValueSchema;
  },
  /**
   * @generated from rpc spec.WktService.GetInt64Value
   */
  getInt64Value: {
    methodKind: "unary";
    input: typeof Int64ValueSchema;
    output: typeof Int64ValueSchema;
  },
  /**
   * @generated from rpc spec.WktService.GetUint64Value
   */
  getUint64Value: {
    methodKind: "unary";
    input: typeof UInt64ValueSchema;
    output: typeof UInt64ValueSchema;
  },
  /**
   * @generated from rpc spec.WktService.GetInt32Value
   */
  getInt32Value: {
    methodKind: "unary";
    input: typeof Int32ValueSchema;
    output: typeof Int32ValueSchema;
  },
  /**
   * @generated from rpc spec.WktService.GetUint32Value
   */
  getUint32Value: {
    methodKind: "unary";
    input: typeof UInt32ValueSchema;
    output: typeof UInt32ValueSchema;
  },
  /**
   * @generated from rpc spec.WktService.GetStringValue
   */
  getStringValue: {
    methodKind: "unary";
    input: typeof StringValueSchema;
    output: typeof StringValueSchema;
  },
  /**
   * @generated from rpc spec.WktService.GetBytesValue
   */
  getBytesValue: {
    methodKind: "unary";
    input: typeof BytesValueSchema;
    output: typeof BytesValueSchema;
  },
  /**
   * @generated from rpc spec.WktService.GetAny
   */
  getAny: {
    methodKind: "unary";
    input: typeof AnySchema;
    output: typeof AnySchema;
  },
  /**
   * @generated from rpc spec.WktService.GetDuration
   */
  getDuration: {
    methodKind: "unary";
    input: typeof DurationSchema;
    output: typeof DurationSchema;
  },
  /**
   * @generated from rpc spec.WktService.GetEmpty
   */
  getEmpty: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc spec.WktService.GetFieldMask
   */
  getFieldMask: {
    methodKind: "unary";
    input: typeof FieldMaskSchema;
    output: typeof FieldMaskSchema;
  },
  /**
   * @generated from rpc spec.WktService.GetTimestamp
   */
  getTimestamp: {
    methodKind: "unary";
    input: typeof TimestampSchema;
    output: typeof TimestampSchema;
  },
  /**
   * @generated from rpc spec.WktService.GetStruct
   */
  getStruct: {
    methodKind: "unary";
    input: typeof StructSchema;
    output: typeof StructSchema;
  },
  /**
   * @generated from rpc spec.WktService.GetListValue
   */
  getListValue: {
    methodKind: "unary";
    input: typeof ListValueSchema;
    output: typeof ListValueSchema;
  },
  /**
   * @generated from rpc spec.WktService.GetValue
   */
  getValue: {
    methodKind: "unary";
    input: typeof ValueSchema;
    output: typeof ValueSchema;
  },
}>;

