// @generated by protoc-gen-es v1.3.0
// @generated from file spec/wkt.proto (package spec, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Any, BoolValue, BytesValue, DoubleValue, Duration, Empty, FieldMask, FloatValue, Int32Value, Int64Value, ListValue, NullValue, proto3, StringValue, Struct, Timestamp, UInt32Value, UInt64Value, Value } from "@bufbuild/protobuf";

/**
 * @generated from message spec.Wkt
 */
export const Wkt = proto3.makeMessageType(
  "spec.Wkt",
  () => [
    { no: 1, name: "fields", kind: "message", T: WktFields },
    { no: 2, name: "oneofs", kind: "message", T: WktOneof },
    { no: 3, name: "maps", kind: "message", T: WktMap },
    { no: 4, name: "repeated", kind: "message", T: WktRepeated },
  ],
);

/**
 * @generated from message spec.WktFields
 */
export const WktFields = proto3.makeMessageType(
  "spec.WktFields",
  () => [
    { no: 1, name: "double_value", kind: "message", T: DoubleValue },
    { no: 2, name: "bool_value", kind: "message", T: BoolValue },
    { no: 3, name: "float_value", kind: "message", T: FloatValue },
    { no: 4, name: "int64_value", kind: "message", T: Int64Value },
    { no: 5, name: "uint64_value", kind: "message", T: UInt64Value },
    { no: 6, name: "int32_value", kind: "message", T: Int32Value },
    { no: 7, name: "uint32_value", kind: "message", T: UInt32Value },
    { no: 8, name: "string_value", kind: "message", T: StringValue },
    { no: 9, name: "bytes_value", kind: "message", T: BytesValue },
    { no: 10, name: "any", kind: "message", T: Any },
    { no: 11, name: "duration", kind: "message", T: Duration },
    { no: 12, name: "empty", kind: "message", T: Empty },
    { no: 13, name: "field_mask", kind: "message", T: FieldMask },
    { no: 14, name: "timestamp", kind: "message", T: Timestamp },
    { no: 15, name: "struct", kind: "message", T: Struct },
    { no: 16, name: "list_value", kind: "message", T: ListValue },
    { no: 17, name: "value", kind: "message", T: Value },
    { no: 18, name: "null_value", kind: "enum", T: proto3.getEnumType(NullValue) },
  ],
);

/**
 * @generated from message spec.WktOneof
 */
export const WktOneof = proto3.makeMessageType(
  "spec.WktOneof",
  () => [
    { no: 1, name: "double_value", kind: "message", T: DoubleValue, oneof: "oneof_value" },
    { no: 2, name: "bool_value", kind: "message", T: BoolValue, oneof: "oneof_value" },
    { no: 3, name: "float_value", kind: "message", T: FloatValue, oneof: "oneof_value" },
    { no: 4, name: "int64_value", kind: "message", T: Int64Value, oneof: "oneof_value" },
    { no: 5, name: "uint64_value", kind: "message", T: UInt64Value, oneof: "oneof_value" },
    { no: 6, name: "int32_value", kind: "message", T: Int32Value, oneof: "oneof_value" },
    { no: 7, name: "uint32_value", kind: "message", T: UInt32Value, oneof: "oneof_value" },
    { no: 8, name: "string_value", kind: "message", T: StringValue, oneof: "oneof_value" },
    { no: 9, name: "bytes_value", kind: "message", T: BytesValue, oneof: "oneof_value" },
    { no: 10, name: "any", kind: "message", T: Any, oneof: "oneof_value" },
    { no: 11, name: "duration", kind: "message", T: Duration, oneof: "oneof_value" },
    { no: 12, name: "empty", kind: "message", T: Empty, oneof: "oneof_value" },
    { no: 13, name: "field_mask", kind: "message", T: FieldMask, oneof: "oneof_value" },
    { no: 14, name: "timestamp", kind: "message", T: Timestamp, oneof: "oneof_value" },
    { no: 15, name: "struct", kind: "message", T: Struct, oneof: "oneof_value" },
    { no: 16, name: "list_value", kind: "message", T: ListValue, oneof: "oneof_value" },
    { no: 17, name: "value", kind: "message", T: Value, oneof: "oneof_value" },
    { no: 18, name: "null_value", kind: "enum", T: proto3.getEnumType(NullValue), oneof: "oneof_value" },
  ],
);

/**
 * @generated from message spec.WktMap
 */
export const WktMap = proto3.makeMessageType(
  "spec.WktMap",
  () => [
    { no: 1, name: "double_value", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: DoubleValue} },
    { no: 2, name: "bool_value", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: BoolValue} },
    { no: 3, name: "float_value", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: FloatValue} },
    { no: 4, name: "int64_value", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Int64Value} },
    { no: 5, name: "uint64_value", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: UInt64Value} },
    { no: 6, name: "int32_value", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Int32Value} },
    { no: 7, name: "uint32_value", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: UInt32Value} },
    { no: 8, name: "string_value", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: StringValue} },
    { no: 9, name: "bytes_value", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: BytesValue} },
    { no: 10, name: "any", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Any} },
    { no: 11, name: "duration", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Duration} },
    { no: 12, name: "empty", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Empty} },
    { no: 13, name: "field_mask", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: FieldMask} },
    { no: 14, name: "timestamp", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Timestamp} },
    { no: 15, name: "struct", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Struct} },
    { no: 16, name: "list_value", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: ListValue} },
    { no: 17, name: "value", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Value} },
    { no: 18, name: "null_value", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "enum", T: proto3.getEnumType(NullValue)} },
  ],
);

/**
 * @generated from message spec.WktRepeated
 */
export const WktRepeated = proto3.makeMessageType(
  "spec.WktRepeated",
  () => [
    { no: 1, name: "double_value", kind: "message", T: DoubleValue, repeated: true },
    { no: 2, name: "bool_value", kind: "message", T: BoolValue, repeated: true },
    { no: 3, name: "float_value", kind: "message", T: FloatValue, repeated: true },
    { no: 4, name: "int64_value", kind: "message", T: Int64Value, repeated: true },
    { no: 5, name: "uint64_value", kind: "message", T: UInt64Value, repeated: true },
    { no: 6, name: "int32_value", kind: "message", T: Int32Value, repeated: true },
    { no: 7, name: "uint32_value", kind: "message", T: UInt32Value, repeated: true },
    { no: 8, name: "string_value", kind: "message", T: StringValue, repeated: true },
    { no: 9, name: "bytes_value", kind: "message", T: BytesValue, repeated: true },
    { no: 10, name: "any", kind: "message", T: Any, repeated: true },
    { no: 11, name: "duration", kind: "message", T: Duration, repeated: true },
    { no: 12, name: "empty", kind: "message", T: Empty, repeated: true },
    { no: 13, name: "field_mask", kind: "message", T: FieldMask, repeated: true },
    { no: 14, name: "timestamp", kind: "message", T: Timestamp, repeated: true },
    { no: 15, name: "struct", kind: "message", T: Struct, repeated: true },
    { no: 16, name: "list_value", kind: "message", T: ListValue, repeated: true },
    { no: 17, name: "value", kind: "message", T: Value, repeated: true },
    { no: 18, name: "null_value", kind: "enum", T: proto3.getEnumType(NullValue), repeated: true },
  ],
);

