// @generated by protoc-gen-knit-ts v0.0.7 with parameter "target=dts"
// @generated from file buf/knit/v1alpha1/options.proto (package buf.knit.v1alpha1, syntax proto3)
/* eslint-disable */

export interface RelationConfig {
    name: string;
}
