// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file buf/knit/v1alpha1/options.proto (package buf.knit.v1alpha1, syntax proto3)
/* eslint-disable */

import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file buf/knit/v1alpha1/options.proto.
 */
export const file_buf_knit_v1alpha1_options = /*@__PURE__*/
  fileDesc("Ch9idWYva25pdC92MWFscGhhMS9vcHRpb25zLnByb3RvEhFidWYua25pdC52MWFscGhhMSIeCg5SZWxhdGlvbkNvbmZpZxIMCgRuYW1lGAEgASgJOl4KCHJlbGF0aW9uEh4uZ29vZ2xlLnByb3RvYnVmLk1ldGhvZE9wdGlvbnMYhQkgASgLMiEuYnVmLmtuaXQudjFhbHBoYTEuUmVsYXRpb25Db25maWdSCHJlbGF0aW9uYgZwcm90bzM", [file_google_protobuf_descriptor]);

/**
 * Describes the message buf.knit.v1alpha1.RelationConfig.
 * Use `create(RelationConfigSchema)` to create a new message.
 */
export const RelationConfigSchema = /*@__PURE__*/
  messageDesc(file_buf_knit_v1alpha1_options, 0);

/**
 * Configuration for the relation that this method resolves. Should only be
 * present for methods that resolve a Knit relation.
 *
 * When this option is present, the name must be non-empty. The entity type
 * for which the relation is resolved is defined as part of the request type.
 * The type of the relation field is defined as part of the response type.
 *
 * Example:
 *   service BarResolverService {
 *     // By convention, the method is named "Get<Base><Relation>". In this
 *     // example, the base type is Foo, and the relation is named bars, thus
 *     // the method is "GetFooBars".
 *     rpc GetFooBars(GetFooBarsRequest) returns (GetFooBarsResponse) {
 *       // This method defines the resolver for a relation named "bars".
 *       option (buf.knit.relation).name = "bars";
 *       // Relation resolvers may not have side effects.
 *       option idempotency_level = NO_SIDE_EFFECTS;
 *     }
 *   }
 *   message GetFooBarsRequest {
 *     // The request *MUST* have a repeated field with tag number 1 named
 *     // "bases". The type must be a message, which is the message type into
 *     // which the relation field will be inserted.
 *     repeated Foo bases = 1;
 *
 *     // May contain other fields with tags 2 and up.
 *   }
 *   message GetFooBarsResponse {
 *     // The response *MUST* have exactly one field, which is a repeated
 *     // field with tag number 1 named "values". The type must be a wrapper
 *     // message with exactly one field with tag number 1. (By convention,
 *     // the wrapper name is "<Base>Result".)
 *     repeated FooResult values = 1;
 *     message FooResult {
 *       // This is the actual field definition that gets injected into the
 *       // base entity type (an element in field "bases" of the request).
 *       //
 *       // This enclosing wrapper message is required in order to support
 *       // optional, repeated, or map fields here. (Because "values" above is
 *       // repeated, and you can't have a repeated field whose element type
 *       // is optional, repeated or map.)
 *       repeated Bar bars = 1;
 *       // This field name must match the relation name.
 *     }
 *   }
 *
 * @generated from extension: buf.knit.v1alpha1.RelationConfig relation = 1157;
 */
export const relation = /*@__PURE__*/
  extDesc(file_buf_knit_v1alpha1_options, 0);

