// @generated by protoc-gen-connect-es v1.0.0
// @generated from file spec/sub/sub.proto (package spec.sub, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SubMessage } from "./sub_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service spec.sub.SubService
 */
export const SubService = {
  typeName: "spec.sub.SubService",
  methods: {
    /**
     * @generated from rpc spec.sub.SubService.SubMethod
     */
    subMethod: {
      name: "SubMethod",
      I: SubMessage,
      O: SubMessage,
      kind: MethodKind.Unary,
    },
  }
};

