// @generated by protoc-gen-connect-es v1.0.0
// @generated from file spec/sub/sub.proto (package spec.sub, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SubMessage } from "./sub_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service spec.sub.SubService
 */
export declare const SubService: {
  readonly typeName: "spec.sub.SubService",
  readonly methods: {
    /**
     * @generated from rpc spec.sub.SubService.SubMethod
     */
    readonly subMethod: {
      readonly name: "SubMethod",
      readonly I: typeof SubMessage,
      readonly O: typeof SubMessage,
      readonly kind: MethodKind.Unary,
    },
  }
};

