// @generated by protoc-gen-es v1.2.0
// @generated from file spec/sub/sub.proto (package spec.sub, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message spec.sub.SubMessage
 */
export const SubMessage = proto3.makeMessageType(
  "spec.sub.SubMessage",
  [],
);

