// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/sub/sub.proto (package spec.sub, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file spec/sub/sub.proto.
 */
export const file_spec_sub_sub = /*@__PURE__*/
  fileDesc("ChJzcGVjL3N1Yi9zdWIucHJvdG8SCHNwZWMuc3ViIgwKClN1Yk1lc3NhZ2UyRQoKU3ViU2VydmljZRI3CglTdWJNZXRob2QSFC5zcGVjLnN1Yi5TdWJNZXNzYWdlGhQuc3BlYy5zdWIuU3ViTWVzc2FnZWIGcHJvdG8z");

/**
 * Describes the message spec.sub.SubMessage.
 * Use `create(SubMessageSchema)` to create a new message.
 */
export const SubMessageSchema = /*@__PURE__*/
  messageDesc(file_spec_sub_sub, 0);

/**
 * @generated from service spec.sub.SubService
 */
export const SubService = /*@__PURE__*/
  serviceDesc(file_spec_sub_sub, 0);

