// @generated by protoc-gen-es v1.3.0
// @generated from file spec/sub/sub.proto (package spec.sub, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message spec.sub.SubMessage
 */
export declare class SubMessage extends Message<SubMessage> {
  constructor(data?: PartialMessage<SubMessage>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "spec.sub.SubMessage";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubMessage;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubMessage;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubMessage;

  static equals(a: SubMessage | PlainMessage<SubMessage> | undefined, b: SubMessage | PlainMessage<SubMessage> | undefined): boolean;
}

