// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=js"
// @generated from file spec/sub/sub.proto (package spec.sub, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spec/sub/sub.proto.
 */
export declare const file_spec_sub_sub: GenFile;

/**
 * @generated from message spec.sub.SubMessage
 */
export declare type SubMessage = Message<"spec.sub.SubMessage"> & {
};

/**
 * Describes the message spec.sub.SubMessage.
 * Use `create(SubMessageSchema)` to create a new message.
 */
export declare const SubMessageSchema: GenMessage<SubMessage>;

/**
 * @generated from service spec.sub.SubService
 */
export declare const SubService: GenService<{
  /**
   * @generated from rpc spec.sub.SubService.SubMethod
   */
  subMethod: {
    methodKind: "unary";
    input: typeof SubMessageSchema;
    output: typeof SubMessageSchema;
  },
}>;

